apiVersion: v1
kind: Service
metadata:
  name: journalnode
spec:
  clusterIP: None
  selector:
    app: journalnode
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: journalnode
spec:
  selector:
    matchLabels:
      app: journalnode
  serviceName: journalnode
  replicas: 1
  template:
    metadata:
      labels:
        app: journalnode
    spec:
      containers:
        - name: journalnode
          image: aespinosa/hadoop:latest
          imagePullPolicy: Always
          command: ["/hadoop-3.2.0/bin/hdfs"]
          args: ["journalnode"]
