---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: server
          image: aespinosa/zookeeper:latest
          imagePullPolicy: Always
          command: ["/zookeeper-3.5.5/bin/zkServer.sh"]
          args: ["start-foreground"]
